version: '3'

services:
  videochat:
    build:
      context: .
      dockerfile: Dockerfile
    image: videochat
    container_name: videochat
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge